var datas = {
        attacks: [{
            name: "tackle",
            power: 30,
            precision: 100,
            type: "normal",
            pp: 30,
            physical_attack: true,
            special_attack: false
            speed_effect: 0,
            dodge_effect: 0,
            physical_attack_effect: 0,
            physical_defense_effect: -10,
            special_defense_effect: 0,
            special_attack_effect: 0,
            paralysis_effect: 0%,
            poison_efect: 0%,
            sleep_effect: 0%,
            fire_effect: 0%,
            bonus_effect: false,
            alteration_effect: false,
            priority: false
        },
        {
            name: "thunderbolt",
            power: 45,
            type: "electrik",
            pp: 25,
            physical_attack: false,
            special_attack: true,
            speed_effect: 0,
            dodge_effect: 0,
            physical_attack_effect: 0,
            physical_defense_effect: -10,
            special_defense_effect: 0,
            special_attack_effect: 0,
            paralysis_effect: 20%,
            poison_efect: 0%,
            sleep_effect: 0%,
            fire_effect: 0%,
            bonus_effect: false,
            alteration_effect: false,
            priority: false
        },
        {
            name: "tail whip",
            power: 0,
            type: "n/a",
            pp: 45,
            physical_attack: false,
            special_attack: false,
            speed_effect: 0,
            dodge_effect, 0,
            physical_attack_effect: 0,
            physical_defense_effect: -10,
            special_defense_effect: 0,
            special_attack_effect: 0,
            paralysis_effect: 0%,
            poison_efect: 0%,
            sleep_effect: 0%,
            fire_effect: 0%,
            bonus_effect: false,
            alteration_effect: true,
            priority: false
        }
    ],
         pokemons: [{
            name: "Eevee",
            type: "normal",
            hp: 40,
            physical_defense: 10,
            special_defense: 15,
            physical_attack: 25,
            special_attack: 5,
            speed: 40,
            weaknes: ["rock","Fighting", "iron"],
            attacks: ["tackle", "quick attack", "tail whip", "bite"]
        },
        {
            name: "Pikachu",
            type: "electrik",
            hp: 46,
            physical_defense: 14,
            special_defense: 25,
            physical_attack: 10,
            special_attack: 25,
            speed: 50,
            weaknes: ["ground","Fighting", "iron"],
            attacks: ["tackle", "quick attack", "tail whip", "thunderbolt"]
        }
    ],
    dreamTeam: ["Pikachu"]
}
